version: '3.7'
services:
  postgres:
    image: postgres:15.3-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - ~/data/traffic_light/postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/data/traffic_light/rabbitmq:/var/lib/rabbitmq
  frontend:
    image: light-traffic-frontend:local
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: ['npm', 'start', 'dev']
  event_store:
    image: light-traffic-event-store:local
    build:
      context: ./event_store
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: ['go', 'run', 'main.go']
    environment:
      - POSTGRES_USER=even_store_usr
      - POSTGRES_PASSWORD=even_store_pass
      - POSTGRES_DB=even_store
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CONTROLLER_TOPIC=controller
      - PROJECTOR_TOPIC=projector
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=1111
    ports:
      - 1111:1111
    volumes:
      - ./event_store:/app
  controller:
    image: light-traffic-controller:local
    build:
      context: ./controller
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - POSTGRES_USER=controller_usr
      - POSTGRES_PASSWORD=controller_pass
      - POSTGRES_DB=controller
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CONTROLLER_TOPIC=controller
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=2222
    ports:
      - 2222:2222
    volumes:
      - ./controller:/app
    command: ['go', 'run', 'main.go']
  projector:
    image: light-traffic-projector:local
    build:
      context: ./projector
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - POSTGRES_USER=projector_usr
      - POSTGRES_PASSWORD=projector_pass
      - POSTGRES_DB=projections
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PROJECTOR_TOPIC=projector
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - ./projector:/app
    command: ['go', 'run', 'main.go']

  