global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'projector'
    metrics_path: /metrics
    static_configs:
      - targets: ['projector:3333']
